import type { SimpleIcon } from 'simple-icons'
import {
  siPython, siR, siPostgresql, siSnowflake, siGooglebigquery,
  siDatabricks, siPandas, siJupyter, siPlotly, siClaude,
  siGooglecolab, siApacheairflow, siLooker, siMetabase,
  siApachesuperset, siMixpanel, siPosthog, siGoogleanalytics,
  siDeepnote, siObservable, siPrefect, siJulia, siPolars,
  siApachespark, siDuckdb, siAirbyte, siMatillion,
  siGooglesheets, siAirtable, siMysql, siSqlite, siQlik, siNumpy,
  siTypescript, siJavascript, siReact, siNextdotjs, siTailwindcss,
  siFramer, siNodedotjs, siNestjs, siExpress, siMongodb, siRedis,
  siPrisma, siDrizzle, siVercel, siDocker, siGit, siGithub, siPostman,
  siJest, siGraphql, siClerk, siGithubcopilot, siCursor, siSvelte,
  siVuedotjs, siVite, siVitest, siTrpc, siSupabase, siZod,
  siFastapi, siPnpm, siTurborepo, siStorybook,
  siPostcss, siLucide, siEslint, siHono, siRailway, siSimpleicons,
  siAlgolia,
} from 'simple-icons'

export const SI_MAP: Record<string, SimpleIcon> = {
  // Data & BI
  python:         siPython,
  r:              siR,
  postgresql:     siPostgresql,
  snowflake:      siSnowflake,
  googlebigquery: siGooglebigquery,
  databricks:     siDatabricks,
  pandas:         siPandas,
  jupyter:        siJupyter,
  plotly:         siPlotly,
  claude:         siClaude,
  googlecolab:    siGooglecolab,
  apacheairflow:  siApacheairflow,
  looker:         siLooker,
  metabase:       siMetabase,
  apachesuperset: siApachesuperset,
  mixpanel:       siMixpanel,
  posthog:        siPosthog,
  googleanalytics:siGoogleanalytics,
  deepnote:       siDeepnote,
  observable:     siObservable,
  prefect:        siPrefect,
  julia:          siJulia,
  polars:         siPolars,
  apachespark:    siApachespark,
  duckdb:         siDuckdb,
  airbyte:        siAirbyte,
  matillion:      siMatillion,
  googlesheets:   siGooglesheets,
  airtable:       siAirtable,
  mysql:          siMysql,
  sqlite:         siSqlite,
  qlik:           siQlik,
  numpy:          siNumpy,
  // App Dev
  typescript:     siTypescript,
  javascript:     siJavascript,
  react:          siReact,
  nextdotjs:      siNextdotjs,
  tailwindcss:    siTailwindcss,
  framer:         siFramer,
  nodedotjs:      siNodedotjs,
  nestjs:         siNestjs,
  express:        siExpress,
  mongodb:        siMongodb,
  redis:          siRedis,
  prisma:         siPrisma,
  drizzle:        siDrizzle,
  vercel:         siVercel,
  docker:         siDocker,
  git:            siGit,
  github:         siGithub,
  postman:        siPostman,
  jest:           siJest,
  graphql:        siGraphql,
  clerk:          siClerk,
  githubcopilot:  siGithubcopilot,
  cursor:         siCursor,
  svelte:         siSvelte,
  vuedotjs:       siVuedotjs,
  vite:           siVite,
  vitest:         siVitest,
  trpc:           siTrpc,
  supabase:       siSupabase,
  zod:            siZod,
  fastapi:        siFastapi,
  pnpm:           siPnpm,
  turborepo:      siTurborepo,
  storybook:      siStorybook,
  postcss:        siPostcss,
  lucide:         siLucide,
  eslint:         siEslint,
  hono:           siHono,
  railway:        siRailway,
  simpleicons:    siSimpleicons,
  algolia:        siAlgolia,
}

// Brand icons absent from simple-icons (trademark/removal)
export const CUSTOM_MAP: Record<string, string> = {
  powerbi: 'M1 14h6v8H1zM9 8h6v14H9zM17 2h6v20h-6z',
}
